### PR TITLE
SetDefaultMinLogLevel based on Serilog's value

### LINKED ISSUE #14: MinimumLevel setting is ignored
Good day,
the Exceptionless Sink only send log messages with level _Warning_ or higher. Lower levels are ignored, due to `Exceptionless.Models.SettingsDictionary.GetMinLogLevel()` defaulting to _Warning_. Other sinks are working correctly. Downgrading to 3.1.0 seems to fix the problem.

Here is a similar issue: [https://github.com/exceptionless/Exceptionless.Net/issues/260](https://github.com/exceptionless/Exceptionless.Net/issues/260), but Constants.SourceContextPropertyName is being set on my side.

### PR DESCRIPTION
**Pull request by alexalok**
Fixes #14

### CODE REVIEW

**Comment by alexalok** [comment]
Oh nevermind, I believe that wouldn't work for folks using 1-step logger initialization. I am not able to find a way around in that case.

**Comment by niemyjski** [comment]
@alexalok What do you mean by 1-step logger initialization?

**Comment by niemyjski** [comment]
If you are using the sink you automatically get the min level. It's only for cases where you are manually creating logs using our API. What is your use case?

**Comment by alexalok** [comment]
> What do you mean by 1-step logger initialization?

In my code I initialize Serilog two times - first time at the very beginning of program execution and second time later when configuration options have been read. My PR code will crash if used during initial initialization because there won't be any level satisfying [this](https://github.com/exceptionless/serilog-sinks-exceptionless/pull/15/files#diff-a29167f554bd1069cd8d8452025d696a9c4edf77f9204b3df04f0438d1a40c52R157) condition.

> If you are using the sink you automatically get the min level. It's only for cases where you are manually creating logs using our API. What is your use case?

My case is related to #14. When first trying this sink I had difficulty understanding why no events were sent. I am now using a modified version from this PR but as I said it won't work for everyone.

**Comment by niemyjski** [comment]
What was causing the crash? Why not just have it call set default log level multiple times? I see no harm in this? Also, please take a look at how we implemented logging with serilog (https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/Program.cs) I'd be curious if this would work for you? Kinda looks like we are double initializing it as well???

**Pull request closed without merging**
